version: '3.5'

services:
  mkweb:
    image: 'mkweb-nginx'
    build: ./
    ports:
      - 8000:80
      - 8803:8803
    container_name: 'mkweb'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf